# Generated by Django 4.0.2 on 2022-03-01 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lidar',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='type',
            field=models.CharField(choices=[('omni', 'Omnidirectional'), ('perspective', 'Perspective'), ('pinhole', 'Pinhole'), ('fisheye', 'Fisheye')], max_length=15),
        ),
    ]
