# Generated by Django 4.0.2 on 2022-03-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_rename_name_camera_cname_rename_type_camera_ctype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lidar',
            old_name='cname',
            new_name='lname',
        ),
    ]
