# Generated by Django 4.0.2 on 2022-03-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_rename_cname_lidar_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lidar',
            name='laser_num',
            field=models.IntegerField(default=0),
        ),
    ]
