# Generated by Django 4.0.2 on 2022-03-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_remove_config_edge_config_remove_config_mi_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='camera',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='calibration.camera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='lidar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='calibration.lidar'),
            preserve_default=False,
        ),
    ]
