# Generated by Django 4.0.2 on 2022-03-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_alter_lidar_laser_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='edge_config',
        ),
        migrations.RemoveField(
            model_name='config',
            name='mi_config',
        ),
        migrations.RemoveField(
            model_name='config',
            name='reproj_config',
        ),
        migrations.RemoveField(
            model_name='config',
            name='reproj_use',
        ),
        migrations.RemoveField(
            model_name='config',
            name='test',
        ),
        migrations.RemoveField(
            model_name='config',
            name='use',
        ),
        migrations.AddField(
            model_name='config',
            name='R_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='check_laser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='discontinuity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='edge_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='show_distribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='t_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='test_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='use_frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='edge_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='end_frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='mi_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='rxyz',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='select_frame_by_hand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='selected',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='skip_line',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='config',
            name='start_frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='verbose',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='vis',
            field=models.CharField(choices=[('mi-r', 'show points within a range, colored by reflectivity'), ('mi', 'show points within a range'), ('edge-e', 'show edge points on image of edges'), ('edge', 'show edge points')], max_length=20),
        ),
    ]
