# Generated by Django 4.0.2 on 2022-03-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0009_config_r1_config_r2_config_r3_config_r4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='degree',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
