# Generated by Django 4.0.2 on 2022-03-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('para', models.JSONField()),
                ('mask', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_frame_by_hand', models.BooleanField()),
                ('start_frame', models.IntegerField()),
                ('end_frame', models.IntegerField()),
                ('use', models.IntegerField()),
                ('selected', models.JSONField()),
                ('verbose', models.BooleanField()),
                ('vis', models.CharField(max_length=20)),
                ('test', models.JSONField()),
                ('scan_path', models.CharField(max_length=200)),
                ('img_path', models.CharField(max_length=200)),
                ('scan_type', models.CharField(max_length=20)),
                ('img_type', models.CharField(max_length=20)),
                ('skip_line', models.IntegerField()),
                ('rxyz', models.BooleanField()),
                ('delimiter', models.CharField(max_length=10)),
                ('mi_use', models.BooleanField()),
                ('edge_use', models.BooleanField()),
                ('reproj_use', models.BooleanField()),
                ('mi_config', models.JSONField()),
                ('edge_config', models.JSONField()),
                ('reproj_config', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LiDAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laser_num', models.IntegerField()),
            ],
        ),
    ]
