# Generated by Django 4.0.2 on 2022-03-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_config_camera_config_lidar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='scan_type',
        ),
    ]
